apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: default
spec:
  ports:
  - nodePort: 32135
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: nginx
  type: NodePort
